### ISSUE TITLE
Make it work if  Ember app is in subfolder of main project.

### ISSUE THREAD

**Issue by SlyDen** [josa42/vscode-ember-related-files#2]
It's not a bug but rather a feature request ...

Present behavior: plugin looks for pieces of app inside `app` or `addon` folder.

Use case: I have a project with API and UI parts in their respective subfolders .. So it would be nice to have some option (?) to tell the plugin where to look for app's components, templates etc.

Does it make sense ?

**Comment by josa42** [comment]
This absolute makes sense. I won't promise anything but I will be looking into it and it should be fairly easy. If you want you can always contribute and open a PR.

**Comment by SlyDen** [comment]
I had a look on the source - quite straightforward ... just getting in VSCode plugin API to be ready for PR :) ... I have to ways in my head to implement it:
1) explicit option in workspace settings .... like ember.project.root or you name it
2) plugin can scan folders tree to find existing Ember apps and addons and use found paths as prefixes for scan. It requires more code, but provides better experience IMHO

Also there can be mix of 1 and 2.

**Comment by josa42** [comment]
The plugin is a little quick and dirty implemented for now, but you could call it straightforward :smile:

For the implementation: I would prefer option no. 2 since it is the better experience. You could scan for a `package.json` and see if `ember-cli` listed as a dependency.

But I would probably except option no. 1 since it is the easier solution.

**Comment by edwinramirez** [comment]
This seems related: https://github.com/josa42/vscode-ember-related-files/issues/7
